networks:
  traefik:
    external: true

services:
  docs:
    build: ./orbitgs
    restart: unless-stopped
    # ports:
    #   - 80:80 # Port of service

    networks:
    - traefik # add to traefik network

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs.rule=Host(`${DOCS_HOST}`)"
      - "traefik.http.routers.docs.entrypoints=websecure"
      - "traefik.http.routers.docs.middlewares=authentik@file"
