networks:
  traefik:
    external: true

services:
  example:
    build: ./orbitgs
    restart: unless-stopped
    # ports:
    #   - 80:80 # Port of service

    networks:
    - traefik # add to traefik network

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.example.rule=Host(`${DOCS_HOST}`)"
      - "traefik.http.routers.example.entrypoints=websecure"